### ISSUE TITLE
Just clarification

### ISSUE THREAD

**Issue by AxelF75** [bri3d/VW_Flash#53]
No Issue, but just a clarification.

The unlock files are the original files from Volkswagen or do they need some modification before using it?

For my car (Eu-spec Audi S3 Limousine) there is no FRF from Audi available (8V0906F_002), so i am not sure if i can go back to stock if something goes wrong. 
I got a bin-file from an unknown source now, but not sure if i can use it.
Thank you!

**Comment by bri3d** [comment]
Original files, no prior modification needed.

If there is no FRF available then indeed, you can only go back to stock if you have secured a bench read. Unfortunately I cannot provide much advice about commercial bench tools. Some produce real / useful BINs, while others scramble, obfuscate, tamper, or damage parts of the software in order to lock you into a tool ecosystem.

One way to check whether your bench read is probably good is to use the "prepare" action in VW_Flash like `python3 VW_Flash.py --action prepare --input_bin bench_read.bin` and then read `flash.log` to see if all of the checksums were valid or not. If checksums had to be corrected then there is something wrong with the file (either the formatting or the actual data/encryption) as obviously a read of a working ECU should not have bad checksums. If the checksums are valid, the file is likely correct.
